(deffacts initial-state
(block A)
(block B)
(block C)
(block D)
(block E)
(block F)
(on-top-of (upper nothing)(lower A))
(on-top-of (upper A)(lower B))
(on-top-of (upper B)(lower C))
(on-top-of (upper C)(lower floor))
(on-top-of (upper nothing)(lower D))
(on-top-of (upper D)(lower E))
(on-top-of (upper E)(lower F))
(on-top-of (upper F)(lower floor))
(goal (move F)(on-top-of C)) )